version: "3"

volumes:
  postgres_data:
#    driver: local
  pgadmin:

services:
  postgres:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_DATABASE=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: always
  keycloak:
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      #KEYCLOAK_HOSTNAME: host.docker.internal:8085/auth
      #KC_HOSTNAME_STRICT_BACKCHANNEL: 'true'
      # KEYCLOAK_FRONTEND_URL: localhost:8085
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - 8085:8080
    volumes:
      - ./themes/registerhtml/register.ftl:/opt/jboss/keycloak/themes/base/login/register.ftl
      - ./themes/registerhtml/login.css:/opt/jboss/keycloak/themes/keycloak/login/resources/css/login.css
      - ./themes/registerhtml/smilebat.png:/opt/jboss/keycloak/themes/keycloak/login/resources/img/smilebat.png
    depends_on:
      - postgres
    networks:
      - postgres
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: always
    
  pgbackups_1:
    image: prodrigestivill/postgres-backup-local
    restart: always
    #user: postgres:postgres # Optional: see below
    volumes:
        - ./pgbackups:/backups
    links:
        - postgres
    depends_on:
        - postgres
    networks:
      - postgres
    environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=password
     #  - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
        - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
        - SCHEDULE=@every 0h10m0s
        - BACKUP_KEEP_DAYS=7
        - BACKUP_KEEP_WEEKS=4
        - BACKUP_KEEP_MONTHS=6
        - HEALTHCHECK_PORT=8080
        
  pgbackups_2:
    image: prodrigestivill/postgres-backup-local
    restart: always
    #user: postgres:postgres # Optional: see below
    volumes:
        - ./pgbackups:/backups
    links:
        - postgres
    depends_on:
        - postgres
    networks:
      - postgres
    environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432
        - POSTGRES_DB=inquisitve
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=password
     #  - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
        - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
        - SCHEDULE=@every 0h1m0s
        - BACKUP_KEEP_DAYS=7
        - BACKUP_KEEP_WEEKS=4
        - BACKUP_KEEP_MONTHS=6
        - HEALTHCHECK_PORT=8080

networks:
  postgres:
    driver: bridge
