version: '3'

services:
  learntribe-inquisitve:
      container_name: learntribe-inquisitve
      image: smilebat96/learntribe-inquisitve:latest
      ports:
        - 8089:8089
      deploy:
        restart_policy:
          condition: on-failure
          delay: 10s
          max_attempts: 5
          window: 120s
      depends_on:
        - keycloak
        - postgres
        - eureka-discovery
      networks:
        - sbdev22_postgres
networks:
  sbdev22_postgres:
    external: true
