version: "3"

services:
  learntribe-inquisitve:
    container_name: learntribe-inquisitve
    image: smilebat96/learntribe-inquisitve:latest
    pull_policy: always
    ports:
      - 8089:8089
    networks:
      - sbdev22_postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-discovery:8761/eureka
      FEIGN_CLIENT_URL_KEYCLOAK: http://host.docker.internal:8085
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inquisitve

  sb-inq:
    container_name: sb-inq
    image: smilebat96/learntribe-inquisitve:latest
    ports:
      - 8089:8080
    networks:
      - sbdev22_postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
    environment:
      #EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-discovery:8761/eureka
      FEIGN_CLIENT_URL_KEYCLOAK: http://host.docker.internal:8085
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/inquisitve
      SPRING_CLOUD_CONSUL_HOST: consul
      KAFKA_STARTUP: true
      KAFKA_SERVER_URL: kafka:29092

  sb-ast:
    container_name: sb-ast
    image: smilebat96/learntribe-assessment-reactor:latest
    ports:
      - 8090:8080
    networks:
      - sbdev22_postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
    environment:
      FEIGN_CLIENT_URL_KEYCLOAK: http://host.docker.internal:8085
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/inquisitve
      SPRING_CLOUD_CONSUL_HOST: consul
      KAFKA_STARTUP: true
      KAFKA_SERVER_URL: kafka:29092

  sb-rsp:
    container_name: sb-rsp
    image: smilebat96/learntribe-resume-processor:latest
    ports:
      - 8091:8080
    networks:
      - sbdev22_postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
    environment:
      FEIGN_CLIENT_URL_KEYCLOAK: http://host.docker.internal:8085
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/inquisitve
      SPRING_CLOUD_CONSUL_HOST: consul
      KAFKA_STARTUP: true
      KAFKA_SERVER_URL: kafka:29092

  sb-oaip:
    container_name: sb-oaip
    image: smilebat96/openai-processor:latest
    ports:
      - 8092:8080
    networks:
      - sbdev22_postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
    environment:
      FEIGN_CLIENT_URL_KEYCLOAK: http://host.docker.internal:8085
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/inquisitve
      SPRING_CLOUD_CONSUL_HOST: consul
      KAFKA_STARTUP: true
      KAFKA_SERVER_URL: kafka:29092
networks:
  sbdev22_postgres:
    external: true
