version: "3"

services:
  nginx:
    container_name: nginx
    image: smilebat96/nginx:latest
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
    networks:
      - sbdev22_postgres
      
  consul:
    #command: -server -bootstrap -advertise=127.0.0.1
    image: consul:latest
    container_name: consul
    ports:
      - 8500:8500
    networks:
      - sbdev22_postgres
      
networks:
  sbdev22_postgres:
    external: true
    
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
