version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx-gw
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
    networks:
      - sbdev22_postgres
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  sbdev22_postgres:
    external: true