version: "3"

services:
  nginx:
    container_name: nginx
    image: smilebat96/nginx:latest
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
    networks:
      - sbdev22_postgres
      
networks:
  sbdev22_postgres:
    external: true

