version: "3"

services:
  app:
    container_name: app
    image: react-app-2
    build:
      context: .
    ports:
      - 3000:80
    networks:
      - sbdev22_postgres
      
networks:
  sbdev22_postgres:
    external: true

