version: "3"

services:
  sb-ui:
    container_name: sb-ui
    image: smilebat96/learntribe-ui-lt:latest
    build:
      context: .
    ports:
      - 3000:80
    networks:
      - sbdev22_postgres
      
networks:
  sbdev22_postgres:
    external: true

