version: '3'

services:
  learntribe-inquisitve:
      container_name: learntribe-inquisitve
      image: smilebat96/learntribe-inquisitve:latest
      ports:
        - 8089:8089
      networks:
        - sbstag_postgres
      deploy:
        restart_policy:
          condition: on-failure
          delay: 10s
          max_attempts: 5
          window: 60s
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-discovery:8761/eureka
        FEIGN_CLIENT_URL_KEYCLOAK: http://www.smilebat.xyz:8085/auth
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/inquisitve
networks:
  sbstag_postgres:
    external: true
