version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - sbstag_postgres
    volumes:
      - ./nginx/dnginxbkp.conf:/etc/nginx/conf.d/default.conf
networks:
  sbstag_postgres:
    external: true