version: '3'

services:
  eureka-discovery:
      container_name: eureka-discovery
      image: smilebat96/cloud-eureka-discovery:latest
      ports:
        - 8761:8761
      deploy:
        restart_policy:
          condition: on-failure
          delay: 10s
          max_attempts: 5
          window: 60s
      networks:
        - sbstag_postgres
  cloud-gateway:
      container_name: cloud-gateway
      image: smilebat96/cloud-gateway:latest
      ports:
        - 8080:8080
      deploy:
        restart_policy:
          condition: on-failure
          delay: 10s
          max_attempts: 5
          window: 60s
      depends_on:
        - eureka-discovery
      networks:
        - sbstag_postgres
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-discovery:8761/eureka
        KEYCLOAK_RESTURL: http://keycloak:8080/auth/realms
        KEYCLOAK_BASEURL: http://www.smilebat.xyz/auth/realms
networks:
  sbstag_postgres:
    external: true
