version: "3"

volumes:
  postgres_data:
    driver: local
  pgadmin:

services:
  postgres:
    container_name: postgres
    image: docker.io/bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_DATABASE=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: always

#  keycloak:
#    container_name: keycloak
#    image: jboss/keycloak:latest
#    environment:
#      DB_VENDOR: postgres
#      DB_ADDR: postgres
#      DB_DATABASE: keycloak
#      DB_USER: keycloak
#      DB_SCHEMA: public
#      DB_PASSWORD: password
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: password
#      KEYCLOAK_HOSTNAME: www.smilebat.xyz
#    ports:
#      - 8085:8080
#    volumes:
#      - ./themes/registerhtml/register.ftl:/opt/jboss/keycloak/themes/base/login/register.ftl
#      - ./themes/registerhtml/login.css:/opt/jboss/keycloak/themes/keycloak/login/resources/css/login.css
#      - ./themes/registerhtml/smilebat.png:/opt/jboss/keycloak/themes/keycloak/login/resources/img/smilebat.png
#    depends_on:
#      - postgres
#    networks:
#      - postgres
#    restart: always
  keycloak:
    image: keycloak-2
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HOSTNAME: www.smilebat.xyz
    ports:
      - 8085:8080
    volumes:
        - ./themes/registerhtml/register.ftl:/opt/keycloak/themes/base/login/register.ftl
        - ./themes/registerhtml/login.css:/opt/keycloak/themes/keycloak/login/resources/css/login.css
        - ./themes/registerhtml/smilebat.png:/opt/keycloak/themes/keycloak/login/resources/img/smilebat.png
    depends_on:
      - postgres
    networks:
      - postgres
    restart: always

 # pgbackups_1:
 #   image: prodrigestivill/postgres-backup-local
 #   restart: always
    #user: postgres:postgres # Optional: see below
 #   volumes:
 #       - ./pgbackups:/backups
 #   links:
 #       - postgres
 #   depends_on:
 #       - postgres
 #   networks:
 #       - postgres
 #   environment:
 #       - POSTGRES_HOST=postgres
 #       - POSTGRES_PORT=5432
 #       - POSTGRES_DB=keycloak
 #       - POSTGRES_USER=keycloak
 #       - POSTGRES_PASSWORD=password
     #  - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
 #       - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
 #       - SCHEDULE=@every 0h5m0s
 #       - BACKUP_KEEP_DAYS=7
 #       - BACKUP_KEEP_WEEKS=2
 #       - BACKUP_KEEP_MONTHS=1
 #       - HEALTHCHECK_PORT=8080

networks:
  postgres:
    driver: bridge
