version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx-n
    volumes:
      - ./nginxcon/nginx.conf:/etc/nginx/nginx.conf
      #- /root/rj/www.smilebat.xyz.crt:/etc/nginx/www.smilebat.xyz.crt
      - /etc/ssl/certs/smilebat.xyz.pem:/etc/nginx/smilebat.xyz.pem
      - /etc/ssl/private/smilebat.xyz.key:/etc/nginx/smilebat.xyz.key
#      - ./build:/var/www/build
    ports:
      - 80:80
      - 443:443
    networks:
      - sbstag23_postgres
  consul:
    #command: -server -bootstrap -advertise=127.0.0.1
    image: consul:latest
    container_name: consul
    ports:
      - 8500:8500
    networks:
      - sbstag23_postgres
networks:
  sbstag23_postgres:
    external: true
