version: "3"

services:
  nginx:
    container_name: nginx
    image: smilebat96/nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - sbstag23_postgres

networks:
  sbstag23_postgres:
    external: true
